#!/usr/bin/env sh
# Render a Homebrew formula for one tagged release of serialwrap.
#
# Usage:
#   packaging/homebrew/render-formula.sh <tag> <path/to/SHA256SUMS> > serialwrap.rb
#
# The release workflow (.github/workflows/release.yml) runs this and attaches
# the result to the GitHub Release as `serialwrap.rb`. To publish it, copy that
# file into a tap repository named `homebrew-serialwrap` (Formula/serialwrap.rb);
# users then install with:
#
#   brew install SheldonChangL/serialwrap/serialwrap
#
# The formula installs the prebuilt release binary, so installing needs neither
# Rust nor Node. Building from source is covered in README.md instead.
set -eu

[ $# -eq 2 ] || {
    echo "usage: $0 <tag> <SHA256SUMS>" >&2
    exit 2
}
tag="$1"
sums="$2"
version="${tag#v}"
repo="SheldonChangL/serialwrap"

sha_for() {
    asset="serialwrap-${tag}-$1.tar.gz"
    sha=$(awk -v a="$asset" '{f=$2; sub(/^\*/, "", f); n=split(f, p, "/"); if (p[n] == a) {print $1; exit}}' "$sums")
    [ -n "$sha" ] || {
        echo "$0: no checksum for $asset in $sums" >&2
        exit 1
    }
    printf '%s\n' "$sha"
}

url_for() {
    printf 'https://github.com/%s/releases/download/%s/serialwrap-%s-%s.tar.gz\n' "$repo" "$tag" "$tag" "$1"
}

mac_arm=$(sha_for aarch64-apple-darwin)
mac_intel=$(sha_for x86_64-apple-darwin)
linux_arm=$(sha_for aarch64-unknown-linux-gnu)
linux_intel=$(sha_for x86_64-unknown-linux-gnu)

cat <<FORMULA
# Generated by packaging/homebrew/render-formula.sh for ${tag}; do not edit by hand.
class Serialwrap < Formula
  desc "Serial-port broker for firmware development"
  homepage "https://github.com/${repo}"
  version "${version}"
  license "MIT"

  on_macos do
    on_arm do
      url "$(url_for aarch64-apple-darwin)"
      sha256 "${mac_arm}"
    end
    on_intel do
      url "$(url_for x86_64-apple-darwin)"
      sha256 "${mac_intel}"
    end
  end

  on_linux do
    on_arm do
      url "$(url_for aarch64-unknown-linux-gnu)"
      sha256 "${linux_arm}"
    end
    on_intel do
      url "$(url_for x86_64-unknown-linux-gnu)"
      sha256 "${linux_intel}"
    end
  end

  def install
    bin.install "serialwrap"
    pkgshare.install "60-serialwrap.rules" if OS.linux?
  end

  def caveats
    <<~EOS
      Start the daemon at login:
        serialwrap service install

      Or run it in the foreground first, to watch it start up:
        serialwrap daemon

      Then open http://127.0.0.1:5590 for the web UI.

      USB-serial driver notes (CH340/CP210x/FTDI) and the Linux dialout/udev
      setup are in the README: https://github.com/${repo}#readme
    EOS
  end

  test do
    assert_match "serialwrap #{version}", shell_output("#{bin}/serialwrap --version")
  end
end
FORMULA
